# Generated by Django 4.2.11 on 2025-04-26 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_e285de_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_schedul_c4290c_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sent_time',
            new_name='read_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='subject',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='max_retries',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='content',
            field=models.TextField(default='', help_text='Use {patient_name}, {doctor_name}, {date}, {time}, etc. as placeholders'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(default='Default Template', max_length=100),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmation', 'Appointment Confirmation'), ('appointment_cancellation', 'Appointment Cancellation')], default='appointment_reminder', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('system_notification', 'System Notification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('template_type', 'is_active')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_be3f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['template_type'], name='notificatio_templat_5e0a58_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_b2a982_idx'),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='days_before',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='hours_before',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='message_template',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='subject_template',
        ),
        migrations.AddIndex(
            model_name='appointmentreminder',
            index=models.Index(fields=['appointment_id'], name='notificatio_appoint_2d4a96_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentreminder',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_9cf988_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentreminder',
            index=models.Index(fields=['status'], name='notificatio_status_948976_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentreminder',
            index=models.Index(fields=['scheduled_time'], name='notificatio_schedul_778890_idx'),
        ),
    ]
